package com.depart.project.service.utils;

public interface ConfigurationManagerConstants {

    String DB_DRIVER_NAME = "DB_DRIVER_NAME";
    String DB_URL = "DB_URL";
    String DB_LOGIN = "DB_LOGIN";
    String DB_PASS = "DB_PASS";
    String ERROR_PAGE_PATH = "ERROR_PAGE_PATH";
    String LOGIN_PAGE_PATH = "LOGIN_PAGE_PATH";
    String MAIN_PAGE_PATH = "MAIN_PAGE_PATH";
    String DEP_PAGE_PATH = "DEP_PAGE_PATH";
    String DEPUPD_PAGE_PATH = "DEPUPD_PAGE_PATH";
    String EMPLOYEE_UPD_PAGE_PATH = "EMPLOYEE_UPD_PAGE_PATH";
    String EMPLOYEE_ADD_PAGE_PATH = "EMPLOYEE_ADD_PAGE_PATH";
    String DEPARTMENT_LISTBUILDER_SERVLET_PATH = "DEPARTMENT_LISTBUILDER_SERVLET_PATH";
    String EMPLOYEES_LISTBUILDER_SERVLET_PATH = "EMPLOYEES_LISTBUILDER_SERVLET_PATH";


}
