package com.depart.project.service.utils;

public interface MessageManagerConstants {

    String BUNDLE_NAME = "messages";
    String LOGIN_ERROR_MESSAGE = "LOGIN_ERROR_MESSAGE";
    String SERVLET_EXCEPTION_ERROR_MESSAGE = "SERVLET_EXCEPTION_ERROR_MESSAGE";
    String IO_EXCEPTION_ERROR_MESSAGE = "IO_EXCEPTION_ERROR_MESSAGE";
    String LOGIN_SAVE_PROBLEM_MESSAGE = "LOGIN_SAVE_PROBLEM_MESSAGE";
    String PASSWORD_SAVE_PROBLEM_MESSAGE = "PASSWORD_SAVE_PROBLEM_MESSAGE";
    String LOGIN_PASSWORD_PROBLEM_MESSAGE = "LOGIN_PASSWORD_PROBLEM_MESSAGE";
    String DEPUPD_PROBLEM_MESSAGE = "DEPUPD_PROBLEM_MESSAGE";
    String DEPTITLE_SAVE_PROBLEM_MESSAGE = "DEPTITLE_SAVE_PROBLEM_MESSAGE";
    String EMPTY_FIELD_MESSAGE = "EMPTY_FIELD_MESSAGE";
    String INVALID_EMAIL_MESSAGE = "INVALID_EMAIL_MESSAGE";
    String FAILED_PASS_CONFIRMATION_MESSAGE = "FAILED_PASS_CONFIRMATION_MESSAGE";
    String INVALID_DATE_MESSAGE = "INVALID_DATE_MESSAGE";
    String NEW_EMPLOYEE_SAVE_SUCCESS_MESSAGE = "NEW_EMPLOYEE_SAVE_SUCCESS_MESSAGE";
    String EMPLOYEE_RECORD_UPDATE_SUCCESS_MESSAGE = "EMPLOYEE_RECORD_UPDATE_SUCCESS_MESSAGE";


}
